# Generated by Django 3.0.4 on 2020-03-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=5)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_salary', models.CharField(max_length=10)),
                ('employee_age', models.CharField(max_length=2)),
                ('profile_img', models.CharField(max_length=1000)),
            ],
        ),
    ]
